#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NavigationAndroid.Resource", IsApplication=true)]

namespace NavigationAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int button = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int fragmentContainer = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int item1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int item2 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int item3 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int main_content = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int nameEditText = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int nameTextView = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int submitButton = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int text = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int toolbar = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int toolbar_bottom = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainOLDToolbar = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Modal = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PopupLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TabFirst = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TabMain = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TabSecond = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Toolbar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int toolbarold = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int popupmenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int DetailPage = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
