#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LayoutAndroidExample.Resource", IsApplication=true)]

namespace LayoutAndroidExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int aButtonMe = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int aButtonMe2 = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int aButtonOrMe = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int aTextBox = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int aTextBox2 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int details = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FrameLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GridLayoutExample = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GridLayoutMultiCellView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GridLayoutSpecifyRowCol = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LayoutExample = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RelativeLayoutExample = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TableLayoutExample = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
